apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomization이 관리할 리소스 목록을 정의
resources:
- hello-app-namespace.yaml
- hello-app-deployment.yaml
- hello-app-service.yaml
images:
- name: lilyshin/hello-app
  newName: lilyshin/hello-app
  newTag: 3dbb9e3
